name: Build-and-Push-to-GitHub-Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run test
      - run: npm run build-all
      - name: Execute dist-to-gh-pages.sh
        run: ./dist-to-gh-pages.sh
        shell: bash